-- Retail Sales Analysis
-- File: 02_joins.sql
-- Purpose: Practice INNER JOIN, LEFT JOIN, grouping, and aggregate functions across tables.

-- Find the product that generated the highest total sales.
SELECT
    p.product,
    SUM(o.sales) AS total_sales
FROM orders o
INNER JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.product
ORDER BY total_sales DESC
LIMIT 1;


-- Show each product name and the total number of orders for that product,
-- including products that have never been ordered.
SELECT
    p.product,
    COUNT(o.order_id) AS order_count
FROM products p
LEFT JOIN orders o
    ON p.product_id = o.product_id
GROUP BY p.product;


-- Find each product name and the total sales generated by that product.
-- Show only products whose total sales are greater than 50.
SELECT
    p.product,
    SUM(o.sales) AS total_sales
FROM products p
INNER JOIN orders o
    ON p.product_id = o.product_id
GROUP BY p.product
HAVING SUM(o.sales) > 50;


-- Find each product name and its highest single order sales value,
-- including products that have never been ordered.
SELECT
    p.product,
    MAX(o.sales) AS highest_order_sales
FROM products p
LEFT JOIN orders o
    ON p.product_id = o.product_id
GROUP BY p.product;


-- Find each product name and the number of distinct customers who ordered it.
-- Show only products ordered by at least 2 distinct customers.
SELECT
    p.product,
    COUNT(DISTINCT o.customer_id) AS distinct_customers
FROM orders o
INNER JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.product
HAVING COUNT(DISTINCT o.customer_id) >= 2;
